### ISSUE TITLE
Consensus Failure: panic: runtime error: index out of range [7] with length 0

### ISSUE THREAD

**Issue by joe-bowman** [Kava-Labs/kava#618]
```
kava_1           | panic: runtime error: index out of range [7] with length 0
kava_1           | 
kava_1           | goroutine 1 [running]:
kava_1           | encoding/binary.bigEndian.Uint64(...)
kava_1           | 	/usr/local/go/src/encoding/binary/binary.go:125
kava_1           | github.com/kava-labs/kava/x/incentive/types.BytesToUint64(...)
kava_1           | 	/go/src/github.com/kava-labs/kava/x/incentive/types/keys.go:43
kava_1           | github.com/kava-labs/kava/x/incentive/keeper.Keeper.GetNextClaimPeriodID(0x193e580, 0xc0001d8310, 0xc0001eb960, 0x193e7c0, 0xc000246790, 0x193c040, 0xc0036571d0, 0xc0001eb960, 0x193c040, 0xc003657140, ...)
kava_1           | 	/go/src/github.com/kava-labs/kava/x/incentive/keeper/keeper.go:93 +0x1be
kava_1           | github.com/kava-labs/kava/x/incentive/keeper.Keeper.ApplyRewardsToCdps.func1(0xc016d986bb, 0x3, 0x13e0e88d, 0xed6b377ee, 0x0, 0x13e0e88d, 0xed6bcb26e, 0x0, 0xc016d986f5, 0x5, ...)
kava_1           | 	/go/src/github.com/kava-labs/kava/x/incentive/keeper/rewards.go:71 +0x3d0
kava_1           | github.com/kava-labs/kava/x/incentive/keeper.Keeper.IterateRewardPeriods(0x193e580, 0xc0001d8310, 0xc0001eb960, 0x193e7c0, 0xc000246790, 0x193c040, 0xc0036571d0, 0xc0001eb960, 0x193c040, 0xc003657140, ...)
kava_1           | 	/go/src/github.com/kava-labs/kava/x/incentive/keeper/keeper.go:73 +0x321
kava_1           | github.com/kava-labs/kava/x/incentive/keeper.Keeper.ApplyRewardsToCdps(0x193e580, 0xc0001d8310, 0xc0001eb960, 0x193e7c0, 0xc000246790, 0x193c040, 0xc0036571d0, 0xc0001eb960, 0x193c040, 0xc003657140, ...)
kava_1           | 	/go/src/github.com/kava-labs/kava/x/incentive/keeper/rewards.go:59 +0x275
kava_1           | github.com/kava-labs/kava/x/incentive.BeginBlocker(0x194f080, 0xc00003e068, 0x19678c0, 0xc00626d440, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
```

Looks like the GetNextClaimPeriodID returns nil byte string from the store.Get([]byte(denom)) and cannot be unmarshalled into a unit64.

I gather you are aware, but placing here for posterity.

**Comment by joe-bowman** [comment]
Fixed in v0.10.0.
